# Generated by Django 3.2.1 on 2021-06-08 06:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_workers_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Construction', 'Construction'), ('Mining', 'Mining'), ('Manufacturing', 'Manufacturing'), ('Agriculture', 'Agriculture'), ('Handy Man', 'Handy Man'), ('Transport', 'Transport'), ('Textile', 'Textile'), ('Other', 'Other')], max_length=100),
        ),
    ]
