# Generated by Django 3.2.1 on 2021-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_alter_workers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='Experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='address_line1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='min_sal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='pref_loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
