# Generated by Django 3.2.1 on 2021-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20210608_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='Date_Of_Birth',
            field=models.DateTimeField(null=True),
        ),
    ]
