# Generated by Django 3.2.1 on 2021-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_alter_workers_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='id',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
