# Generated by Django 3.2.1 on 2021-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20210608_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='Do_you_have',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='gender',
            field=models.CharField(max_length=200),
        ),
    ]
