# Generated by Django 3.2.1 on 2021-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20210608_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Phone_Number', models.CharField(max_length=10, null=True)),
                ('Email', models.EmailField(default='abc@xyz.com', max_length=254, null=True)),
                ('Address_line1', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Education_Level', models.CharField(max_length=2, null=True)),
                ('Minimum_Expected_Salary', models.CharField(max_length=100, null=True)),
                ('Date_of_Birth', models.DateField(default='yyyy-mm-dd', null=True)),
                ('Previous_Work_Experience', models.CharField(max_length=1000, null=True)),
                ('Categories', models.ManyToManyField(blank=True, null=True, to='registrations.Skills')),
                ('Preferred_Work_Location', models.ManyToManyField(null=True, to='registrations.Work_Loc')),
            ],
        ),
    ]
