# Generated by Django 3.2.1 on 2021-06-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_worker_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_model',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
