# Generated by Django 3.2.1 on 2021-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_worker_model_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_model',
            name='Date_of_Birth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
