# Generated by Django 3.2.1 on 2021-06-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_alter_worker_model_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_model',
            name='photo',
        ),
    ]
