# Generated by Django 3.2.1 on 2021-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_remove_worker_model_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_model',
            name='Categories',
        ),
        migrations.AddField(
            model_name='worker_model',
            name='Categories',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='worker_model',
            name='Preferred_Work_Location',
        ),
        migrations.AddField(
            model_name='worker_model',
            name='Preferred_Work_Location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
