# Generated by Django 3.2.1 on 2021-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_auto_20210608_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_model',
            name='Preferred_Work_Location',
        ),
        migrations.AddField(
            model_name='worker_model',
            name='Preferred_Work_Location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
