# Generated by Django 3.2.1 on 2021-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auto_20210608_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
