# Generated by Django 3.2.1 on 2021-06-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_auto_20210609_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='pref_loc',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
